name: Cypress Tests
on:
  workflow_dispatch:
    #This trigger helps show the "Run Workflow" button under the github actions page. Hence enabling to trigger workflow manually.
    #reference guide: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run or create output files for artifacts
        run: |
          mkdir ./cypress
          echo '111111' > ./cypress/cypress_1.html
          echo '2222' > ./cypress/cypress_2.html
          echo '3333' > ./cypress/cypress_3.html

      - name: upload E2E test reports from individual parallel exec chunk ${{matrix.chunk}}
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-reports
          path: ./cypress

